Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,7 +11,6 @@ jobs:
 
     env:
       MAVEN_HOME: /opt/maven
-      #DOCKER_REGISTRY: 18.216.88.91:9002
       DOCKER_IMAGE: my-app
 
     steps:
@@ -46,7 +45,7 @@ jobs:
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
 
     - name: Build Docker Image
-      run: docker build -t 18.216.88.91:9002/repository/gitactions/${{ env.DOCKER_IMAGE }}:latest .
+      run: docker build -t 18.216.88.91:8082/repository/test/${{ env.DOCKER_IMAGE }}:latest .
 
     - name: Log in to Nexus
       run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login -u ${{ secrets.NEXUS_USERNAME }} --password-stdin http://18.216.88.91:9002
@@ -55,5 +54,5 @@ jobs:
     #   # env:
     #   #   NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
     #   run: |
-    #     docker login 18.216.88.91:9002 -u admin --password admin ||
-    #     docker push 18.216.88.91:9002/repository/gitactions/${{ env.DOCKER_IMAGE }}:latest || { echo "Docker push failed"; exit 1; }
+    #     docker login 18.216.88.91:8082 -u admin --password admin ||
+    #     docker push 18.216.88.91:8082/repository/test/${{ env.DOCKER_IMAGE }}:latest || { echo "Docker push failed"; exit 1; }
